// <auto-generated />
namespace TDP_CRUD2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fristmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fristmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201708201935343_fristmigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
